#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line entry point to grepros.

------------------------------------------------------------------------------
This file is part of grepros - grep for ROS bag files and live topics.
Released under the BSD License.

@author      Erki Suurjaak
@created     31.10.2021
@modified    02.11.2021
------------------------------------------------------------------------------
"""
from grepros import main


if "__main__" == __name__:
    main.run()
